### PR TITLE
Build in c++14

### PR DESCRIPTION
**Pull request by springmeyer**
Testing building against c++14 osrm-backend: https://github.com/Project-OSRM/osrm-backend/pull/2691

### CODE REVIEW

**Comment by TheMarex** [comment]
@springmeyer is this good to merge?

**Comment by springmeyer** [comment]
👍  good to merge @TheMarex

**Comment by springmeyer** [comment]
Followup doc update after this merges at #233

**Comment by springmeyer** [comment]
Because osrm-backend is already building in c++14 we already have a new base level of requirements per #233. Therefore it is time to merge this.

**Pull request merged**
