### PR TITLE
API documentation [not ready] 

### PR DESCRIPTION
**Pull request by morganherlocker**
Done
---

- add comments to C++ code
- create an API.md file
- create a basic html site for the API documenting examples, methods, and return types
- add a dev-dependency for [documentationjs](http://documentation.js.org/)
- add an npm script for generating API.md and index.html by running `npm run doc`

Remaining
---

- [x] double check param types to make sure I understood them all correctly
- [x] double check return object types against real output
- [ ] group items within the OSRM class together; move typedefs for result objects to the bottom
- [ ] root page with install instructions?
- [ ] document generating documentation :smile: 

screenshot 2015-07-23 17 25 45

### CODE REVIEW

**Comment by TheMarex** [comment]
You might have already seen this, but https://github.com/Project-OSRM/osrm-backend/wiki/Server-api contains a reference to most of the parameters and objects returned. Let me know if there are some subtle differences - the APIs should be as similar as possible.

**Comment by TheMarex** [comment]
Hey @morganherlocker what is the status of this? Any way I can help?

**Comment by morganherlocker** [comment]
Really close on this. Only blocker I have at the moment is a potential issue upstream in documentationjs, but it's nothing big. More soon.

**Comment by TheMarex** [comment]
@morganherlocker is the documentationjs issue resolved?

**Comment by freenerd** [comment]
@morganherlocker can this be pushed over the edge? would be great to release with osrm release next week :rocket:

**Comment by morganherlocker** [comment]
hitting this today

**Comment by TheMarex** [comment]
@morganherlocker can I lend a hand? Would like to do a new `node-osrm` release tomorrow at the latest.

**Comment by morganherlocker** [comment]
I committed a "hand-formatted" API.md to this branch. The remaining documentationjs issues are blocking the release of the full site for now, and I have not had a chance to tackle them, but linking to the API.md will be a good 80% solution for now.

**Pull request closed without merging**
