### PR TITLE
Updates XCode 7.3 -> 8.2 on Travis

### PR DESCRIPTION
**Pull request by daniel-j-h**
Trying to see if it helps for https://github.com/Project-OSRM/node-osrm/issues/289.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
https://travis-ci.org/Project-OSRM/node-osrm/jobs/194425064#L1149-L1151

The issue changed from the compiler error in the contractor assertion, to a Boost internal IPC assertion.

```
# route: routes Berlin using shared memory
[assert][0x7000175c7000] /Users/travis/build/Project-OSRM/node-osrm/mason_packages/headers/boost/1.61.0/include/boost/interprocess/sync/posix/condition.hpp:175
in: void boost::interprocess::ipcdetail::posix_condition::do_wait(boost::interprocess::ipcdetail::posix_mutex &): res == 0
ok 34 null
ok 35 should be truthy
# route: routes Berlin with geometry compression
libc++abi.dylib: terminating
make: *** [test] Abort trap: 6
make-test failed with 2
```

**Comment by daniel-j-h** [comment]
With the updated Boost 1.63

```
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libsystem/1.63.0.tar.gz...
```

still seeing the assertion in Boost.Interprocess

```
[assert][0x70001610a000] /Users/travis/build/Project-OSRM/node-osrm/mason_packages/headers/boost/1.63.0/include/boost/interprocess/sync/posix/condition.hpp:175
in: void boost::interprocess::ipcdetail::posix_condition::do_wait(boost::interprocess::ipcdetail::posix_mutex &): res == 0
libc++abi.dylib: terminating
```

**Comment by danpat** [comment]
@oxidase has found the root cause of this assertion here: https://github.com/Project-OSRM/osrm-backend/pull/3627

It's not XCode 7.3/8.0 specific, but an OSX bug.  I'm 👍  on just updating to XCode 8.x anyway.

@daniel-j-h Good to merge this change, the real problem needs to be fixed in `osrm-backend` and the test suite.

**Comment by daniel-j-h** [comment]
Okay :+1:

**Pull request merged**
