### PR TITLE
bump to reflect v4.5.0 release cycle of OSRM

### PR DESCRIPTION
**Pull request by DennisOSRM**

### CODE REVIEW

**Comment by DennisOSRM** [comment]
@springmeyer could you give the build a little bit of your hawk-eye magic?

```log
using g++-4.8 version : 4.8
g++-4.8: No such file or directory
dirname: missing operand
Try `dirname --help' for more information.
```

**Comment by springmeyer** [comment]
Builds are working, but seeing the below error running the tests. @DennisOSRM - do you have ideas here?

```
terminate called after throwing an instance of 'osrm::exception'
  what():  ERROR occured in profile script:
test/data/car.lua:148: attempt to index field 'tags' (a nil value)
Aborted
```

**Comment by DennisOSRM** [comment]
Thanks @springmeyer. 

Looks like one of the duplicated dependencies is outdated. Will investigate tomorrow.

**Comment by springmeyer** [comment]
@DennisOSRM okay, FWIW I booted up an ubuntu precise machine and could not replicate the abort. I see:

```
$ git branch
  master
* v4.5.0

$ npm test

> osrm@4.5.0-final test /home/ubuntu/node-osrm
> mocha -R spec



  ✓ throws if new keyword is not used 
  ✓ throws if necessary files do not exist 
  ✓ throws if insufficient coordinates given (45ms)
  ✓ routes Berlin (52ms)
  - routes Berlin using shared memory
  ✓ routes Berlin with options (52ms)
  ✓ distance table in Berlin (52ms)
  ✓ routes Berlin with hints (53ms)
  ✓ nearest (53ms)
  ✓ locate (46ms)

  9 passing (365ms)
  1 pending

```

**Comment by DennisOSRM** [comment]
Same here. Thanks @springmeyer

**Comment by springmeyer** [comment]
Okay, this branch should now be passing nicely on travis. The problem was that I accidentally pushed to/looked at the build log for master. This `v4.5.0` branch has the updated `lua.car` profile that avoids the error.

**Comment by DennisOSRM** [comment]
Cool. Thanks @springmeyer for figuring this out.

**Pull request merged**
