### PR TITLE
Reenable shared memory test

### PR DESCRIPTION
**Pull request by TheMarex**
This re-enables the shared memory test. Needs soon to be released OSRM ```4.6.1```, as the default parameter for OSRM previously was to use shared memory, but the last release accidentally changed that.

### CODE REVIEW

**Comment by TheMarex** [comment]
@springmeyer I now know why we disabled that test. It fails on Mac OS obviously. Can we enable/disable tests based on OS?

**Comment by springmeyer** [comment]
Yes, @TheMarex - we can do:

```js
if (process.platform !== 'darwin') {
  // run actual test
} else {
  // create phony test target that skips it - nice to show that it is being skipped
  // could be done like: https://github.com/mapbox/node-pre-gyp/blob/master/test/build.test.js#L384
  it.skip('test name' + app.args, function() {});
}
```

However, can you remind me why OS X will not work. It it worth considering getting it to work?

**Comment by TheMarex** [comment]
@springmeyer I was under the impression that we used linux syscalls to setup shared memory. But we seem to be boost interprocess now, which _should_ abstract over that.

**Comment by springmeyer** [comment]
@TheMarex - okay, so perhaps enable the test on linux, and create a ticket to investigate getting working on OS X soonish?

**Comment by springmeyer** [comment]
just confirmed (before merging this fix into the sudo-false branch) that if this happens again (a crash on travis) we'll get lovely backtraces in the logs automatically: https://github.com/Project-OSRM/node-osrm/pull/90#issuecomment-95651722

**Pull request merged**
