### PR TITLE
Ship Profiles, resolves #242

### LINKED ISSUE #242: Shipping OSRM Profiles
Why don't we ship osrm-backend profiles in `node-osrm`?

`node-osrm` ships `osrm-backend` binaries such as `osrm-extract` and `osrm-contract` which need to be run for making use of `node-osrm`. We recommend using the binaries shipping with `node-osrm` since it's easier to use and the chances for a version mismatch are non-existent.

But then why don't we ship profiles (i.e. `car.lua` and all Lua modules we require) needed for running `osrm-extract`? Having the user manually grab profiles from the `osrm-backend` repo. is not particularly user-friendly.

Can't we just ship profiles along the binaries to get a working setup out of the box?

### PR DESCRIPTION
**Pull request by daniel-j-h**
For https://github.com/Project-OSRM/node-osrm/issues/242.

I _think_ changing the `bootstrap.sh` as I did in this changeset should be good enough.

@springmeyer @TheMarex the next time we do a release we should see them getting uploaded to `npm` via `npm publish`? And users will get them and can use them as outlined in the docs, correct?

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Adding a .npmignore to this branch, too (was already ticketed in #208).

**Comment by TheMarex** [comment]
This probably needs a rebase and should work then, right=

**Comment by daniel-j-h** [comment]
In theory yes. Practically speaking I don't know what we have to and want to ship here specifically. Would you be so kind and have a look here and test this locally: `npm pack` will generate an archive of what's getting uploaded to npm. We have to make sure this is correct, otherwise our next 5.5 release will break.

**Comment by TheMarex** [comment]
Rebased this on #271 and ported all logic to the Makefile + `prepublish` hook.

**Pull request merged**
