### PR TITLE
Update node-cmake to v2.x.x

### LINKED ISSUE #279: Installing via npm fails to build from source
Hey hey, maybe I'm missing something obvious, but `osrm@5.5.2` doesn't want to build when falling back to building from source during an npm install (whereas `osrm@5.4.3` installs just fine).

To make sure it's not a general issue with my system, I cloned node-osrm and ran the build there, which succeeded without any warnings or errors. The only thing I found was a warning when running the tests: `[warn] .hsgr was prepared with different build.` – but I'm thinking that's related to me having a different version of `osrm-backend` installed already, and `pkg-config` using that one instead of the local one that was just built (?) – that's a different issue, though.

**Environment**

```
$ node --version
v7.3.0

$ npm --version
4.1.1
```

I have an existing `osrm-backend` install via Homebrew (which is a different version),
in case that's relevant to this particular case.

```
$ which osrm-extract
/usr/local/bin/osrm-extract

$ which osrm-contract
/usr/local/bin/osrm-contract

$ which osrm-datastore
/usr/local/bin/osrm-datastore

$ pkg-config libosrm --variable=prefix
/usr/local/Cellar/osrm-backend/5.4.3
```

**Expected Behavior**

As it can't find pre-built binaries for `osrm@5.5.2` against `node@7` (as there are only binaries for `node@4`, according to #238 and #226), it would fall back to building from source (and succeed in doing so).

**Actual Behavior**

It fails to build from source, with the following error (full output log below):

```
CMake Error at CMakeLists.txt:95 (find_package):
  By not providing "FindNodeJS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NodeJS", but
  CMake did not find one.

  Could not find a package configuration file provided by "NodeJS" with any
  of the following names:

    NodeJSConfig.cmake
    nodejs-config.cmake

  Add the installation prefix of "NodeJS" to CMAKE_PREFIX_PATH or set
  "NodeJS_DIR" to a directory containing one of the above files.  If "NodeJS"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/Jonas/Work/baikonur/node_modules/osrm/build/CMakeFiles/CMakeOutput.log".
See also "/Users/Jonas/Work/baikonur/node_modules/osrm/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:20: build/Release/node-osrm.node] Error 1
```

<details>
  <summary>Full Output Log</summary>
  <p>
<pre><code>$ npm i osrm
npm http request GET https://registry.npmjs.org/osrm
npm http 304 https://registry.npmjs.org/osrm
npm http request GET https://registry.npmjs.org/node-cmake
npm http request GET https://registry.npmjs.org/nan
npm http request GET https://registry.npmjs.org/node-pre-gyp
npm http 304 https://registry.npmjs.org/node-cmake
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/node-pre-gyp
npm http request GET https://registry.npmjs.org/mothership
npm http request GET https://registry.npmjs.org/which
npm http request GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/mothership
npm http 304 https://registry.npmjs.org/which
npm http 200 https://registry.npmjs.org/lodash
npm http request GET https://registry.npmjs.org/find-parent-dir
npm http 304 https://registry.npmjs.org/find-parent-dir
npm http request GET https://registry.npmjs.org/isexe
npm http 304 https://registry.npmjs.org/isexe
npm http request GET https://registry.npmjs.org/nopt
npm http request GET https://registry.npmjs.org/npmlog
npm http request GET https://registry.npmjs.org/rc
npm http request GET https://registry.npmjs.org/request
npm http request GET https://registry.npmjs.org/tar
npm http request GET https://registry.npmjs.org/semver
npm http request GET https://registry.npmjs.org/tar-pack
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/tar-pack
npm http 304 https://registry.npmjs.org/request
npm http request GET https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/abbrev
npm http request GET https://registry.npmjs.org/console-control-strings
npm http request GET https://registry.npmjs.org/gauge
npm http request GET https://registry.npmjs.org/set-blocking
npm http request GET https://registry.npmjs.org/are-we-there-yet
npm http 304 https://registry.npmjs.org/console-control-strings
npm http 304 https://registry.npmjs.org/gauge
npm http 304 https://registry.npmjs.org/are-we-there-yet
npm http 304 https://registry.npmjs.org/set-blocking
npm http request GET https://registry.npmjs.org/delegates
npm http request GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/delegates
npm http 304 https://registry.npmjs.org/readable-stream
npm http request GET https://registry.npmjs.org/core-util-is
npm http request GET https://registry.npmjs.org/buffer-shims
npm http request GET https://registry.npmjs.org/isarray
npm http request GET https://registry.npmjs.org/process-nextick-args
npm http request GET https://registry.npmjs.org/util-deprecate
npm http request GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/buffer-shims
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/string_decoder
npm http request GET https://registry.npmjs.org/has-unicode
npm http request GET https://registry.npmjs.org/object-assign
npm http request GET https://registry.npmjs.org/signal-exit
npm http request GET https://registry.npmjs.org/supports-color
npm http request GET https://registry.npmjs.org/string-width
npm http request GET https://registry.npmjs.org/wide-align
npm http request GET https://registry.npmjs.org/strip-ansi
npm http request GET https://registry.npmjs.org/aproba
npm http 304 https://registry.npmjs.org/has-unicode
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/signal-exit
npm http 304 https://registry.npmjs.org/wide-align
npm http 304 https://registry.npmjs.org/string-width
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/aproba
npm http request GET https://registry.npmjs.org/code-point-at
npm http request GET https://registry.npmjs.org/is-fullwidth-code-point
npm http 304 https://registry.npmjs.org/code-point-at
npm http 304 https://registry.npmjs.org/is-fullwidth-code-point
npm http request GET https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/number-is-nan
npm http request GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http request GET https://registry.npmjs.org/deep-extend
npm http request GET https://registry.npmjs.org/strip-json-comments
npm http request GET https://registry.npmjs.org/ini
npm http request GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/ini
npm http request GET https://registry.npmjs.org/aws-sign2
npm http request GET https://registry.npmjs.org/caseless
npm http request GET https://registry.npmjs.org/extend
npm http request GET https://registry.npmjs.org/combined-stream
npm http request GET https://registry.npmjs.org/aws4
npm http request GET https://registry.npmjs.org/forever-agent
npm http request GET https://registry.npmjs.org/form-data
npm http request GET https://registry.npmjs.org/har-validator
npm http request GET https://registry.npmjs.org/http-signature
npm http request GET https://registry.npmjs.org/isstream
npm http request GET https://registry.npmjs.org/is-typedarray
npm http request GET https://registry.npmjs.org/json-stringify-safe
npm http request GET https://registry.npmjs.org/hawk
npm http request GET https://registry.npmjs.org/qs
npm http request GET https://registry.npmjs.org/stringstream
npm http request GET https://registry.npmjs.org/mime-types
npm http request GET https://registry.npmjs.org/oauth-sign
npm http request GET https://registry.npmjs.org/uuid
npm http request GET https://registry.npmjs.org/tunnel-agent
npm http request GET https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/aws4
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/is-typedarray
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/oauth-sign
npm http request GET https://registry.npmjs.org/delayed-stream
npm http 304 https://registry.npmjs.org/delayed-stream
npm http request GET https://registry.npmjs.org/asynckit
npm http 304 https://registry.npmjs.org/asynckit
npm http request GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm http request GET https://registry.npmjs.org/pinkie-promise
npm http request GET https://registry.npmjs.org/commander
npm http request GET https://registry.npmjs.org/chalk
npm http request GET https://registry.npmjs.org/is-my-json-valid
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http request GET https://registry.npmjs.org/ansi-styles
npm http request GET https://registry.npmjs.org/escape-string-regexp
npm http request GET https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/has-ansi
npm http request GET https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http request GET https://registry.npmjs.org/generate-object-property
npm http request GET https://registry.npmjs.org/xtend
npm http request GET https://registry.npmjs.org/jsonpointer
npm http request GET https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/generate-function
npm http request GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/is-property
npm http request GET https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/pinkie
npm http request GET https://registry.npmjs.org/cryptiles
npm http request GET https://registry.npmjs.org/sntp
npm http request GET https://registry.npmjs.org/boom
npm http request GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http request GET https://registry.npmjs.org/jsprim
npm http request GET https://registry.npmjs.org/assert-plus
npm http request GET https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/sshpk
npm http request GET https://registry.npmjs.org/extsprintf
npm http request GET https://registry.npmjs.org/json-schema
npm http request GET https://registry.npmjs.org/verror
npm http 304 https://registry.npmjs.org/extsprintf
npm http 304 https://registry.npmjs.org/verror
npm http 304 https://registry.npmjs.org/json-schema
npm http request GET https://registry.npmjs.org/asn1
npm http request GET https://registry.npmjs.org/dashdash
npm http request GET https://registry.npmjs.org/getpass
npm http request GET https://registry.npmjs.org/ecc-jsbn
npm http request GET https://registry.npmjs.org/jsbn
npm http request GET https://registry.npmjs.org/bcrypt-pbkdf
npm http request GET https://registry.npmjs.org/jodid25519
npm http request GET https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/jsbn
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/bcrypt-pbkdf
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/jodid25519
npm http 304 https://registry.npmjs.org/getpass
npm http request GET https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/punycode
npm http request GET https://registry.npmjs.org/block-stream
npm http request GET https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/fstream
npm http request GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/graceful-fs
npm http request GET https://registry.npmjs.org/fstream-ignore
npm http request GET https://registry.npmjs.org/uid-number
npm http request GET https://registry.npmjs.org/once
npm http request GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/fstream-ignore
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/uid-number
npm http 304 https://registry.npmjs.org/debug
npm http request GET https://registry.npmjs.org/ms
npm http 304 https://registry.npmjs.org/ms

> osrm@5.5.2 preinstall /Users/Jonas/Work/baikonur/node_modules/.staging/osrm-d9b66aff
> npm install node-pre-gyp

npm http request GET https://registry.npmjs.org/mkdirp
npm http request GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mkdirp
npm http request GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits
npm http request GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/glob
npm http request GET https://registry.npmjs.org/fs.realpath
npm http request GET https://registry.npmjs.org/path-is-absolute
npm http request GET https://registry.npmjs.org/minimatch
npm http request GET https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/fs.realpath
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/minimatch
npm http request GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/wrappy
npm http request GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/brace-expansion
npm http request GET https://registry.npmjs.org/balanced-match
npm http request GET https://registry.npmjs.org/concat-map
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map
osrm@5.5.2 /Users/Jonas/Work/baikonur/node_modules/.staging/osrm-d9b66aff
└─┬ node-pre-gyp@0.6.32
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.0.9
  ├─┬ npmlog@4.0.2
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ ├── delegates@1.0.0
  │ │ └── readable-stream@2.2.2
  │ ├── console-control-strings@1.1.0
  │ ├─┬ gauge@2.7.2
  │ │ ├── aproba@1.0.4
  │ │ ├── has-unicode@2.0.1
  │ │ ├── object-assign@4.1.0
  │ │ ├── signal-exit@3.0.2
  │ │ ├─┬ string-width@1.0.2
  │ │ │ ├── code-point-at@1.1.0
  │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │ │   └── number-is-nan@1.0.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.0.0
  │ │ ├── supports-color@0.2.0
  │ │ └── wide-align@1.1.0
  │ └── set-blocking@2.0.0
  ├─┬ rc@1.1.6
  │ ├── deep-extend@0.4.1
  │ ├── ini@1.3.4
  │ ├── minimist@1.2.0
  │ └── strip-json-comments@1.0.4
  ├─┬ request@2.79.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.5.0
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.2
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├── has-ansi@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@4.0.1
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.1
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.10.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.0
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.13
  │ │ └── mime-db@1.25.0
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.3.0
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.4.3
  │ └── uuid@3.0.1
  ├─┬ rimraf@2.5.4
  │ └─┬ glob@7.1.1
  │   ├── fs.realpath@1.0.0
  │   ├── inflight@1.0.6
  │   ├─┬ minimatch@3.0.3
  │   │ └─┬ brace-expansion@1.1.6
  │   │   ├── balanced-match@0.4.2
  │   │   └── concat-map@0.0.1
  │   ├── once@1.4.0
  │   └── path-is-absolute@1.0.1
  ├── semver@5.3.0
  ├─┬ tar@2.2.1
  │ ├── block-stream@0.0.9
  │ ├─┬ fstream@1.0.10
  │ │ └── graceful-fs@4.1.11
  │ └── inherits@2.0.3
  └─┬ tar-pack@3.3.0
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── fstream-ignore@1.0.5
    ├─┬ once@1.3.3
    │ └── wrappy@1.0.2
    ├─┬ readable-stream@2.1.5
    │ ├── buffer-shims@1.0.0
    │ ├── core-util-is@1.0.2
    │ ├── isarray@1.0.0
    │ ├── process-nextick-args@1.0.7
    │ ├── string_decoder@0.10.31
    │ └── util-deprecate@1.0.2
    └── uid-number@0.0.6

> osrm@5.5.2 install /Users/Jonas/Work/baikonur/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || make

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.5.2/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.5.2/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.5.2/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/Jonas/Work/baikonur/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/Jonas/Work/baikonur/node_modules/osrm/node_modules/request/request.js:986:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:362:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Jonas/Work/baikonur/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/Jonas/Work/baikonur/node_modules/osrm
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.5.2/Release/node-v51-darwin-x64.tar.gz
mkdir -p build &&\
 cd build &&\
 cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBOSRM=On &&\
 VERBOSE=1 make -j4 &&\
 cd ..
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using osrm v5.5.2
-- Downloading to /Users/Jonas/Work/baikonur/node_modules/osrm/deps/osrm-backend-Release
-- Installing to /tmp/osrm-backend
Cloning into '/Users/Jonas/Work/baikonur/node_modules/osrm/deps/osrm-backend-Release'...
Note: checking out 'v5.5.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 434a3a63... Make Travis buildit.
-- Building libosrm as subproject.
-- Enabling mason
-- Building on a 64 bit system
CMake Warning at deps/osrm-backend-Release/CMakeLists.txt:153 (message):
  GNU gold linker isn't available.

-- Configuring OSRM in release mode
-- Configuring release mode optimizations
-- Performing Test LTO_AVAILABLE
-- Performing Test LTO_AVAILABLE - Success
-- Performing Test LTO_WORKS
-- Performing Test LTO_WORKS - Success
-- LTO working
CMake Warning at deps/osrm-backend-Release/CMakeLists.txt:246 (message):
  LLVM specific binutils not found.

-- Using unknown linker, not setting linker optimizations
-- Set Architecture to x64 on OS X
-- linking against libc++
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Installing dependencies via mason
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/boost/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/headers/boost/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libfilesystem/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libfilesystem/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libiostreams/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libiostreams/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libprogram_options/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libprogram_options/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libregex/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libregex/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libtest/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libtest/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libdate_time/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libdate_time/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libthread/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libthread/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/boost_libsystem/1.61.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/boost_libsystem/1.61.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/stxxl/1.4.1.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/stxxl/1.4.1...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/expat/2.2.0.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/expat/2.2.0...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/lua/5.2.4.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/lua/5.2.4...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/luabind_lua524/e414c57bcb687bb3091b7c55bbff6947f052e46b.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/luabind_lua524/e414c57bcb687bb3091b7c55bbff6947f052e46b...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/bzip2/1.0.6.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/bzip2/1.0.6...
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/tbb/43_20150316.tar.gz...
-- [Mason] Unpacking package to ../../mason_packages/osx-x86_64/tbb/43_20150316...
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5")
CMake Error at CMakeLists.txt:95 (find_package):
  By not providing "FindNodeJS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NodeJS", but
  CMake did not find one.

  Could not find a package configuration file provided by "NodeJS" with any
  of the following names:

    NodeJSConfig.cmake
    nodejs-config.cmake

  Add the installation prefix of "NodeJS" to CMAKE_PREFIX_PATH or set
  "NodeJS_DIR" to a directory containing one of the above files.  If "NodeJS"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/Users/Jonas/Work/baikonur/node_modules/osrm/build/CMakeFiles/CMakeOutput.log".
See also "/Users/Jonas/Work/baikonur/node_modules/osrm/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:20: build/Release/node-osrm.node] Error 1
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "osrm"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! osrm@5.5.2 install: 'node-pre-gyp install --fallback-to-build=false || make'
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the osrm@5.5.2 install script 'node-pre-gyp install --fallback-to-build=false || make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jonas/Work/baikonur/npm-debug.log
</code></pre>
  </p>
</details>

### PR DESCRIPTION
**Pull request by jhermsmeier**
Fixes #279 – Installing via npm fails to build from source

**Changes**
- Added `NodeJS.cmake` generated by `ncmake update`,
  as `find_package` support has been removed (see [node-cmake#removed-features](https://github.com/cjntaylor/node-cmake#removed-features))
- Renamed the `.node` binding from `node-osrm` to `node_osrm` due to it being used for namespace generation, resulting in build errors as it contained a dash

### CODE REVIEW

**Comment by cordovapolymer** [comment]
Please accept this pull request if it finally fixes #279

**Comment by jhermsmeier** [comment]
There currently appear to be some issues with `node-cmake` on Travis CI under Linux – I'm looking into ironing that out, but the Mac OS builds seem to be fine.

**Comment by jhermsmeier** [comment]
@cordovapolymer It builds just fine for me (without a `--global` install) – also, why are you trying to install it globally? If you don't mind, could you try and see what happens if you just run `npm install` for this one – does that build?

**Comment by cordovapolymer** [comment]
@jhermsmeier answered you in https://github.com/Project-OSRM/node-osrm/issues/279, as for a global build, I wouldn't mind if it could build and install locally, although it's not a big issue for my setup. When I just run `npm install` it builds both node-osrm and osrm-backend, but I want node-osrm to be build with my existing osrm-backend.

**Comment by jhermsmeier** [comment]
> When I just run `npm install` it builds both node-osrm and osrm-backend, but I want node-osrm to be build with my existing osrm-backend.

It won't use your preinstalled `osrm-backend` by default (and adding `-g` won't do that either), see https://github.com/Project-OSRM/node-osrm#using-an-existing-local-osrm-backend. Also, keep in mind that you'll have to have the same version of `osrm-backend` installed as the module specifies (in this case v5.5.4).

This pull request is about making `node-osrm` work under node v7+ (or other versions without pre-built `osrm-backend` binaries available) when installed as a dependency.

**Comment by cordovapolymer** [comment]
It won't use your preinstalled osrm-backend by default (and adding -g won't do that either), see https://github.com/Project-OSRM/node-osrm#using-an-existing-local-osrm-backend. Also, keep in mind that you'll have to have the same version of osrm-backend installed as the module specifies (in this case v5.5.4).
It doesn't build with lastest OSRM as well..

> This pull request is about making node-osrm work under node v7+ (or other versions without pre-built osrm-backend binaries available) when installed as a dependency.
At a first look I thought it would solve my issue as well, I'll have to wait for another fix or get info how to fix it myself.

**Comment by daniel-j-h** [comment]
We merged node-osrm into the osrm-backend repo. - I updated node-cmake to v2 in doing so.

Can you check if the node-osrm integration in osrm-backend works for you? It's still in its early staged, here are some prs and issues tagged nodejs:

- https://github.com/Project-OSRM/osrm-backend/pulls?q=is%3Apr+label%3ANodeJs+is%3Aclosed
- https://github.com/Project-OSRM/osrm-backend/issues?q=is%3Aissue+is%3Aopen+label%3ANodeJs

**Pull request closed without merging**
